enscript --line-numbers --highlight=java --word-wrap  -c Sources/Former/src/bitset.zig -p view/bitset.ps
ps2pdf view/bitset.ps view/bitset.pdf
enscript --line-numbers --highlight=java --word-wrap -c Sources/Former/src/formparser.zig  -p view/formparser.ps
ps2pdf view/formparser.ps view/formparser.pdf
enscript --line-numbers --highlight=java --word-wrap -c Sources/Former/src/lexer.zig  -p view/lexer.ps     
ps2pdf view/lexer.ps view/lexer.pdf
enscript --line-numbers --highlight=java --word-wrap -c Sources/Former/src/oldparser.zig  -p view/oldparser.ps
ps2pdf view/oldparser.ps view/oldparser.pdf
enscript --line-numbers --highlight=java --word-wrap -c Sources/Former/src/parser.zig  -p view/parser.ps 
ps2pdf view/parser.ps view/parser.pdf
enscript --line-numbers --highlight=java --word-wrap -c Sources/Former/src/tableparser.zig -p view/tableparser.ps
ps2pdf view/tableparser.ps view/tableparser.pdf
enscript --line-numbers --highlight=java --word-wrap -c Sources/Former/src/token.zig -p view/token.ps
ps2pdf view/token.ps view/token.pdf
enscript --line-numbers --highlight=java --word-wrap -c Sources/Former/src/value.zig -p view/value.ps
ps2pdf view/value.ps view/value.pdf
enscript --line-numbers --highlight=java --word-wrap -c Sources/Informal/logical_parser.infr -p view/logical_parser.ps
ps2pdf view/logical_parser.ps view/logical_parser.pdf
enscript --line-numbers --highlight=python --word-wrap -c Sources/Informal/meta_parser.ifi -p view/meta_parser.ps 
ps2pdf view/meta_parser.ps view/meta_parser.pdf
enscript --line-numbers --highlight=python --word-wrap -c Sources/Informal/parser.ifi -p view/ifi_parser.ps
ps2pdf view/ifi_parser.ps view/ifi_parser.pdf

# <HR>
# <ADDRESS>Generated by <A HREF="http://www.iki.fi/~mtr/genscript/">GNU Enscript 1.6.6</A>.</ADDRESS>
# -w html -1r