# Generated by Django 2.2 on 2020-01-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='slug',
            field=models.SlugField(default='default', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='view',
            name='remote_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
