# Generated by Django 2.2 on 2020-01-08 04:56

from django.db import migrations, models
import uuid


# S/O 35281003: Setting up uuid by default will result in duplicate values
def create_uuid(apps, schema_editor):
    View = apps.get_model('editor', 'View')
    for view in View.objects.all():
        view.uuid = uuid.uuid4()
        view.save()


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20200106_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='view',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
