# Generated by Django 2.2 on 2020-01-08 04:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20200106_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
