# Generated by Django 2.2 on 2020-08-21 22:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_view_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=64)),
                ('expr', models.TextField(blank=True)),
                ('guard_expr', models.TextField(blank=True)),
                ('docs', models.TextField(blank=True)),
                ('params', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, size=None)),
                ('param_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.App')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Cell')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('base_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_cells', to='editor.Cell')),
                ('ref_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_cells', to='editor.Cell')),
            ],
        ),
        migrations.CreateModel(
            name='Ancestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor_cells', to='editor.Cell')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_cells', to='editor.Cell')),
            ],
        ),
        migrations.AddField(
            model_name='view',
            name='root_cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.Cell'),
        ),
    ]
