# Generated by Django 2.2 on 2020-08-22 01:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_auto_20200821_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='param_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cell',
            name='params',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
        migrations.AlterUniqueTogether(
            name='ancestor',
            unique_together={('child', 'ancestor')},
        ),
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together={('base_cell', 'ref_cell')},
        ),
    ]
