compile:
    wasm win.wat -o win.wasm

view:
    wat2wasm win.wat -v

dis:
    wasm-objdump win.wasm -d

inspect:
    wasmer inspect win.wasm

compile-native:
    wasmtime compile --target x86_64-unknown-linux --cranelift-enable skylake win.wat

bench:
    hyperfine --warmup 3 'wasmtime run win.cwasm --allow-precompiled --invoke add 2 3'

setup:
    sudo apt install wabt
    sudo apt install wasmtime
    # Setup ocaml and the GC wasm proposal for the version of "wasm" used here.