compile:
    wat2wasm wasmin.wat -o wasmin.wasm

view:
    wat2wasm wasmin.wat -v

dis:
    wasm-objdump wasmin.wasm -d

inspect:
    wasmer inspect wasmin.wasm

compile-native:
    wasmtime compile --target x86_64-unknown-linux --cranelift-enable skylake wasmin.wat

bench:
    hyperfine --warmup 3 'wasmtime run wasmin.cwasm --allow-precompiled --invoke add 2 3'

setup:
    sudo apt install wabt
    sudo apt install wasmtime
    # Setup ocaml and the GC wasm proposal for the version of "wasm" used here.