
@gen filename:
    python informal.py > {{filename}}.mlir


# Usage - just build hello
@build filename:
    mlir-opt {{filename}}.mlir --convert-func-to-llvm | \
    mlir-translate --mlir-to-llvmir > {{filename}}.ll
    # Compile the LLVM IR to an object file:
    clang {{filename}}.ll --output {{filename}}.out
    chmod +x {{filename}}.out

@run filename:
    just gen {{filename}}
    just build {{filename}}
    ./{{filename}}.out