[package]
name = "arevel"
version = "0.1.0"
authors = ["Feni Varughese <feni727@gmail.com>"]
edition = "2018"
include = [
  "avs/**/*",
]



[workspace]
members = [
  "avs",
  "site",
  "avgen",
  "runtime",
  "experiments"
]

[dependencies]
runtime = { path = "runtime" }
avs = { path = "avs" }
flatbuffers = "0.6.0"


# Allow us to catch panics in parsing, eval etc. without bringing down the system.
[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"

